version: 0.2
phases: 
  install: 
    runtime-versions:
      java: corretto21
    commands: 
      - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $REPOSITORY_DOMAIN --domain-owner $REPOSITORY_OWNER --region $REPOSITORY_REGION --query authorizationToken --output text`
      - mkdir -p ~/.m2/settings.xml
      - cp backend/settings.xml /root/.m2/settings.xml
  build: 
    commands:
      - cd backend
      - mvn clean package -Dnative -DskipTests -s settings.xml --batch-mode
cache:
  paths: 
    - '/root/.m2/**/*'

artifacts:
  files: 
    - backend/target/**/*
  discard-paths: no
  name: backend-$(date +%Y-%m-%d) 