version: 0.2
phases: 
  install: 
    commands: 
      - unset CI
      - ls -la
  build: 
    commands:
      - echo "deploying to s3"
      - export DEPLOY_DIR=`echo $CODEBUILD_SOURCE_VERSION | tr ':' '_'`
      - aws s3 cp dist/* $BUCKET_URL/${PROJECT_NAME}/$DEPLOY_DIR/

