version: 0.2
phases: 
  install: 
    commands: 
      - unset CI
      - ls -la
  build: 
    commands:
      - pwd
      - echo "deploying to s3 $BUCKET_URL"
      - | 
        aws s3 cp frontend/dist $BUCKET_URL/$PROJECT_NAME/$GITHUB_COMMID_ID/ --recursive
      - | 
        export FRONTEND_IMAGE_TAG="$FRONTEND_REPOSITORY_URL:$GITHUB_BRANCH_NAME"
        echo "Building tag $FRONTEND_IMAGE_TAG"
        docker build --tag $FRONTEND_IMAGE_TAG -f $CODEBUILD_SRC_DIR_GITHUB_SRC/frontend/docker/Dockerfile .
       

