version: 0.2
phases: 
  install: 
    commands: 
      - unset CI
      - ls -la
  build: 
    commands:
      - pwd
      - echo "deploying to s3 $BUCKET_URL"
      - | 
        aws s3 cp $CODEBUILD_SRC_DIR_frontend_build_output/frontend/dist $BUCKET_URL/$PROJECT_NAME/$GITHUB_COMMID_ID/ --recursive
      - | 
        export FRONTEND_IMAGE_TAG="$FRONTEND_REPOSITORY_URL:$GITHUB_BRANCH_NAME"
        echo "Building tag $FRONTEND_IMAGE_TAG"
      - docker build --tag $FRONTEND_IMAGE_TAG -f $CODEBUILD_SRC_DIR/frontend/docker/Dockerfile $CODEBUILD_SRC_DIR_frontend_build_output
      - docker push $FRONTEND_IMAGE_TAG 
      - |
        export BACKEND_IMAGE_TAG="$BACKEND_REPOSITORY_URL:$GITHUB_BRANCH_NAME" 
        echo "Building tag $BACKEND_IMAGE_TAG"
        docker build --tag $BACKEND_IMAGE_TAG -f $CODEBUILD_SRC_DIR/backend/src/main/docker/Dockerfile.native $CODEBUILD_SRC_DIR_backend_build_output/backend
        docker push $BACKEND_IMAGE_TAG

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_LOGIN_URL
      - docker pull $FRONTEND_REPOSITORY_URL:$GITHUB_BRANCH_NAME || true
      - docker pull $BACKEND_REPOSITORY_URL:$GITHUB_BRANCH_NAME || true