version: 0.2
phases: 
  install: 
    commands: 
      - unset CI
      - ls -la
  build: 
    commands:
      - pwd
      - | 
        export FRONTEND_IMAGE_TAG="$ECR_REPOSITORY_URL:$GITHUB_BRANCH_NAME-$GITHUB_COMMIT_ID" 
        export FRONTEND_BUILD_HOME=`echo $(printenv -0 "CODEBUILD_SRC_DIR_$BUILD_OUTPUT_NAME")`
        echo "Building tag $FRONTEND_IMAGE_TAG"
      - docker build --tag $FRONTEND_IMAGE_TAG -f $CODEBUILD_SRC_DIR/frontend/docker/Dockerfile $FRONTEND_BUILD_HOME
      - docker push $FRONTEND_IMAGE_TAG 
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_LOGIN_URL
      - docker pull $ECR_REPOSITORY_URL:$GITHUB_BRANCH_NAME-$GITHUB_COMMIT_ID || true