version: 0.2
phases: 
  install: 
    runtime-versions:
      nodejs: 20
    commands: 
      - unset CI
      - cd frontend
      - yarn 
  build: 
    commands:
      - yarn build
cache:
  paths: 
    - frontend/node_modules

artifacts:
  files: 
    - dist/**/*
  base-directory: frontend
  discard-paths: no
  name: frontend-$(date +%Y-%m-%d) 
