version: 0.2
phases: 
  install: 
    runtime-versions:
      nodejs: 20
    commands: 
      - unset CI
      - cd frontend
      # - |
      #   echo "yarn 2.x"
      #   yarn config set npmRegistryServer "$NPM_REPOSITORY_URL"
      #   export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $NPM_REPOSITORY_DOMAIN --domain-owner $NPM_REPOSITORY_OWNER --region $NPM_REPOSITORY_REGION --query authorizationToken --output text`
      #   yarn config set "npmRegistries[\"$NPM_REPOSITORY_URL\"].npmAuthToken" "${CODEARTIFACT_AUTH_TOKEN}"
      #   yarn config set "npmRegistries[\"$NPM_REPOSITORY_URL\"].npmAlwaysAuth" "true"
      #   yarn config list
      - | 
        echo "yarn 1.x"
        rm yarn.lock -fv
        yarn config set registry "$NPM_REPOSITORY_URL"
        echo "registry \"$NPM_REPOSITORY_URL\"" >> .yarnrc
        aws codeartifact login --tool npm --repository $NPM_REPOSITORY_NAME --domain $NPM_REPOSITORY_DOMAIN --domain-owner $NPM_REPOSITORY_OWNER --region $NPM_REPOSITORY_REGION
        echo "always-auth=true" >> ~/.npmrc
        yarn  --prefer-offline
  build: 
    commands:
      - yarn build
cache:
  paths: 
    - frontend/node_modules/**/*

artifacts:
  files: 
    - dist/**/*
  base-directory: frontend
  discard-paths: no
  name: frontend-$(date +%Y-%m-%d) 
