version: 0.2
phases: 
  install: 
    runtime-versions:
      nodejs: standard:5.0 
    commands: 
      - unset CI
      - cd frontend
      - yarn 
  build: 
    commands:
      - yarn build
cache:
  paths: 
    - frontend/node_modules

artifacts:
  files: 
    - build/**
  base-directory: frontend
  discard-paths: yes
  name: frontend-$(date +%Y-%m-%d) 
